### ISSUE TITLE
Feature Request Add Welcome Screen without Asset tag

### ISSUE THREAD

**Issue by colorenz** [dan-snelson/dialog-scripts#11]
Hi maybe we can add a normal welcome dialog without the asset tag field and the asset tag functions?

Maybe something like this. That the window then also closes automatically and the deployment begins.

Best Regards

welcomeTitle="Hello!"
welcomeMessage="Nice to meet. Nice that you start at company acme"
appleInterfaceStyle=$( /usr/bin/defaults read /Users/"${loggedInUser}"/Library/Preferences/.GlobalPreferences.plist AppleInterfaceStyle 2>&1 )

if [[ "${appleInterfaceStyle}" == "Dark" ]]; then
    welcomeIcon="https://gmfsmortgage.com/wp-content/uploads/2018/10/ACME-Corporation-fake-logo-150x150.jpg"
else
    welcomeIcon="https://gmfsmortgage.com/wp-content/uploads/2018/10/ACME-Corporation-fake-logo-150x150.jpg"
fi

dialogWelcomeCMD="$dialogApp \
--title \"$welcomeTitle\" \
--message \"$welcomeMessage\" \
--icon \"$welcomeIcon\" \
--iconsize 198 \
--button1text \"Continue\" \
--infotext \"$scriptVersion\" \
--ontop \
--timer 30 \
--hidetimerbar \
--titlefont 'size=30' \
--messagefont 'size=18' \
--quitkey k \
--commandfile \"$welcomeCommandFile\" "

**Comment by dan-snelson** [comment]
Thanks for the Feature Request, @colorenz.

I have some ideas … let me try to get something going.

**Comment by dan-snelson** [comment]
Thanks for your patience, @colorenz, please test-drive [v1.3.2 RC1](https://github.com/dan-snelson/dialog-scripts/blob/v1.3.2-rc/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash).

(You'll most likely just want to [delete these lines](https://github.com/dan-snelson/dialog-scripts/blob/v1.3.2-rc/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L105-L170).)

**Comment by dan-snelson** [comment]
Resolved in `v1.5.0`. ([Thanks for your patience](https://snelson.us/2022/11/setup-your-mac-via-swiftdialog-1-5-0/#yoyo-code).)
