### ISSUE TITLE
Feature Request: Restart button

### ISSUE THREAD

**Issue by mvught** [dan-snelson/dialog-scripts#15]
**Is your feature request related to a problem? Please describe.**
Option to enable Reboot after completed enrollment

**Comment by dan-snelson** [comment]
Thanks for the Feature Request, @mvught.

Is something like [Forced and Dismissible Log Out, Restart or Shut Down Prompts](https://snelson.us/2022/07/log-out-restart-shut-down/) over-kill?

(I'm thinking of just adding these options to **Parameter 6**: `Completion Action`.)

**Comment by riddl0rd** [comment]
Hallo Dan,

It would be nice to precent the enduser with a option to restart after enrollment complete!!!

Also thanks for the hard work you put in this project

**Comment by dan-snelson** [comment]
Greetings, @mvught and @riddl0rd!

What level of interest do either of you have in testing **in-progress**, **not-for-production** code?

**Comment by dan-snelson** [comment]
@mvught and @riddl0rd:

Will you both please test drive [`1.3.1`](https://github.com/dan-snelson/dialog-scripts/blob/issue-15/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash)? (Located in the **issue-15** branch.)

(As you can imagine, testing forced-restarts is fairly inconvenient.)

Version `1.3.1` (17-Nov-2022)
- Added a `completionAction` function (i.e., [Wait, Sleep, Logout, Restart or Shutdown](https://github.com/dan-snelson/dialog-scripts/blob/issue-15/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L533-L596))
- Removed `jamfDisplayMessage` function and reverted `dialogCheck` function to use `osascript` (with an enhanced error message)
- Swapped `blurscreen` for `moveable` in Debug Mode
- Replaced "Installing …" with "Updating …" for `recon`-flavored `trigger`
- Changed "Updating Inventory" to "Computer Inventory" in final `listitem`
- Increased Debug Mode speed

**Comment by iDrewbs** [comment]
Hi @dan-snelson Tested out 1.3.1 using the default wait `completionAction`, but after clicking the Quit button the script continues to run and has to be manually terminated. The final output when it hangs is `Honoring wait behavior`

**Comment by dan-snelson** [comment]
Thanks for the feedback, @iDrewbs.

Let me double-check and better document what I'm observing.

**Comment by master-vodawagner** [comment]
I’m interested in this feature too, happy to help.

could this be extended to the failure dialog if presented?

**Comment by dan-snelson** [comment]
Just committed a change; please re-re-try now, @iDrewbs.

Thanks for the offer, @master-vodawagner; please do.

Yes, this change has been added to both successful and failure dialogs.

Currently, a hard-coded `wait` command has been added [here](https://github.com/dan-snelson/dialog-scripts/blob/issue-15/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L434-L436) and [here](https://github.com/dan-snelson/dialog-scripts/blob/issue-15/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L447-L449).

(To me, if anything fails, the user should be required to manually acknowledge the failure; I'm interested in every one's feedback.)

**Comment by dan-snelson** [comment]
Made another commit; thanks for all the assistance.

**Comment by dan-snelson** [comment]
Thanks for the feedback, @jared-a-young.

1. So, on a successful completion, if you're using `Restart` for `completionActionOption`, you'd _also_ like to **require** user-interaction? (My initial thought is that for this use-case, you'd use `Restart Confirm` for `completionActionOption`.)

1. Good idea on having the button reflect the setting of `completionActionOption`; I'll take a look.

**Comment by dan-snelson** [comment]
When capturing an Asset Tag and clicking **Quit**, ignore the `completionActionOption`.

**Comment by dan-snelson** [comment]
When using `Restart` for `completionActionOption` via Self Service, a Cocoa error `132001` is observed.

**Comment by owainiorwerth** [comment]
Thanks, both! 

Just to expand on this slightly - the restart/logout confirm parameter relies on the user to hit the relevant option in the macOS pop-up dialogue - which they could easily dismiss (I don't trust end users one bit!)

Using just the restart or logout parameter ensures that the action requested is carried out but it would be great if it only did it once the user clicked the button, which displayed the text of what was going to happen next i.e. logout or restart. 

I can envisage new employees not paying attention to their macs and then turning back around to see the mac restarting or logged out without expecting that to happen (then contacting us needlessly to say 'hey this just happened, is everything ok?')

**Comment by dan-snelson** [comment]
## [1.3.1 RC2](https://github.com/dan-snelson/dialog-scripts/blob/issue-15/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash)
- Signficantly enchanced **Completion Action** options
  - :white_check_mark: Addresses [Issue 15](https://github.com/dan-snelson/dialog-scripts/issues/15) (thanks, @mvught, @riddl0rd, @iDrewbs and @master-vodawagner)
  - :man_dancing: Dynamically set `button1text` based on the value of `completionActionOption` (thanks, @jared-a-young)
  - :new: Three new flavors: **Shut Down**, **Restart** or **Log Out**
    - :rotating_light: **Forced:** Zero user-interaction
      - Added brute-force `killProcess "Self Service"`
      - Added `hack` to allow Policy Logs to be shipped to Jamf Pro server
    - :warning: **Attended:** Forced, but only _after_ user-interaction (thanks, @owainiorwerth)
      - Added `hack` to allow Policy Logs to be shipped to Jamf Pro server
    - :bust_in_silhouette: **Confirm:** Displays built-in macOS _user-dismissible_ dialog box
  - Sleep
  - Wait (default)
- Improved **Debug Mode** behavior
  - :bug: `DEBUG MODE |` now only displayed as `infotext` (i.e., bottom, left-hand corner)
  - `completionAction` informational-only with simple dialog box (thanks, @_____?)
  - Swapped `blurscreen` for `moveable`
  - General peformance increases
- Miscellaneous Improvements
  - Removed `jamfDisplayMessage` function and reverted `dialogCheck` function to use `osascript` (with an enhanced error message)
  - Replaced "Installing …" with "Updating …" for `recon`-flavored `trigger`
  - Changed "Updating Inventory" to "Computer Inventory" for `recon`-flavored `listitem`
  - Changed exit code to `1` when user quits "Welcome" screen
  - Changed `welcomeIcon` URLs
  - Add way too many [emojis](https://github-emoji-picker.vercel.app) to ChangeLog

**Comment by iDrewbs** [comment]
I did some testing of the new Completion Action Options in RC2:

CompletionActionOption Feedback:
- Wait - When using this option, Button1 text says "Wait" at the end, which could confuse the user thinking they need to wait for something. It would be better to read "Quit" or "Close"
- Log Out Confirm - The logout confirmation prompt is triggered before clicking the "Log Out" button. Should this be updated, so the logout confirmation is triggered once the button is clicked?
- Restart Confirm - The Restart confirmation prompt is. being triggered before clicking the "Restart" button. Should this be updated, so the Restart confirmation is triggered once the button is clicked?
- Shut Down Confirm - The Shut Down confirmation prompt is triggered before clicking the "Shut Down" button. Should this be updated, so the Shut Down confirmation is triggered once the button is clicked?
- Shut Down Attended - This works as expected. However, the progresstext at the bottom includes "Complete! Please restart..." instead of "Complete Please Shut Down"
- Shut Down - This works as expected, however, the progresstext at the bottom includes "Complete! Please Restart...". It should probably indicate something like "Complete! Shutting Down your Mac..."

The remaining options work as expected:
- Sleep - This works great
- Log Out Attended - This works great. 
- Log Out - this works great. 
- Restart Attended - This works great. 
- Restart - this works great.

**Comment by dan-snelson** [comment]
Thanks for your thorough testing and detailed feedback, @iDrewbs!

If I haven't warn out my welcome, please test [`1.3.1 RC3`](https://github.com/dan-snelson/dialog-scripts/blob/issue-15/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash). (Also paging @mvught, @riddl0rd, @master-vodawagner and @owainiorwerth.)

I previously observed your findings with the "Confirm" flavors, but couldn't replicate them just now on physical hardware running macOS `13.0.1 (22A400)` with Jamf Pro `10.42.1`.

**Comment by iDrewbs** [comment]
Just tested all of the new options and everything looks great! All the verbiage matches the CompletionActionOptions perfectly. 
The behavior with the "Confirm" flavors may just be a symptom of my test Mac since I have been doing a lot of various testing. I'll try it with a few more, but I don't think it needs to be considered a blocker. 
Let me know if I can do any further testing!

**Comment by riddl0rd** [comment]
Just tested the Restart Confirm option configured within the paramater 6 option in the policy, and it works perfect with macOS 13.0.1.

Also will test out the other triggers in the morning.

Thank you!

**Comment by dan-snelson** [comment]
Feature Request completed with [v1.3.1](https://github.com/dan-snelson/dialog-scripts/blob/main/Setup%20Your%20Mac/CHANGELOG.md#131)

**Comment by dan-snelson** [comment]
Thanks for the feedback, @owainiorwerth.

What behavior are you seeing if your run [v1.5.0-rc1](https://github.com/dan-snelson/dialog-scripts/blob/v1.5.0-rc/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash) as-is via Terminal?

**Comment by owainiorwerth** [comment]
OK did a fair bit of testing today with different setups but concluded that...

Restart and Log Out Attended work fine if running the script locally (in both Debug True /
or False) - hard coded variables.

Restart and Log Out Attended work fine if manually calling the policy via Self-Service (in both Debug True /
or False) - hard coded variables. 

Restart and Log Out Attended don't work if automatically calling the policy, which kicks in at Enrollment Complete in our environment.  It's a simple policy which just calls the script - hard coded variables. The swift dialog pkg is installed at pre-stage enrollment.

**Comment by dan-snelson** [comment]
Thanks for the additional details, @owainiorwerth.

Please see [Implementation Notes](https://snelson.us/2022/11/setup-your-mac-via-swiftdialog-1-3-0/#implementation-notes); I'm **not** testing using `enrollmentComplete` (but right off I can't see why it wouldn't work).

Will you please open a fresh issue? Thanks.
