### ISSUE TITLE
Disable Mission Control when not in debug mode

### ISSUE THREAD

**Issue by jared-a-young** [dan-snelson/dialog-scripts#16]
**Is your feature request related to a problem? Please describe.**
when enrolling a computer a user can "get out" of the setup screen by using mission control on the trackpad and essentially get to activity monitor to kill swiftDialog from running

**Describe the solution you'd like**
it would be nice to have a parameter option to disable mission control during setup

**Describe alternatives you've considered**
config profile or script but its not consistent

**Additional context**

**Comment by dan-snelson** [comment]
Setup Your Mac is leveraging `swiftDialog`'s built-in capabilities for `blurscreen.`

Please see [swiftDialog Issue No. 198](https://github.com/bartreardon/swiftDialog/issues/198).

**Comment by dan-snelson** [comment]
Closing; see https://github.com/bartreardon/swiftDialog/issues/198#issuecomment-1320691169
