### ISSUE TITLE
Icon hash not available on prem jamf 

### ISSUE THREAD

**Issue by mani2care** [dan-snelson/dialog-scripts#2]
Hi Dan really nice work , i just tried testing your script and dialog i have issue with enabling the icon with hash unable to grab from on prem jamf and its getting only as like below.

https://xxxxxxx/icon?id=25 

any alternate solution for this?

**Comment by mani2care** [comment]
<img width="1440" alt="Screenshot 2022-08-20 at 4 56 24 PM" src="https://user-images.githubusercontent.com/52978899/185744139-7fb80333-01e1-4200-84b0-c228718d0465.png">


i just mentioned the ID value as 25 but its not taking it 

is there any way ti find the selfservice icon in local machine were its stored on

**Comment by dan-snelson** [comment]
@mani2care:

We, too, are hosted on-prem.

Please advise if [Cloud Services Connection](https://docs.jamf.com/10.40.0/jamf-pro/documentation/Cloud_Services_Connection.html?hl=icon%20service) has been enabled.

- [Cisco AnyConnect Secure Mobility Client](https://ics.services.jamfcloud.com/icon/hash_13b91657996eef085f117a4914a49a153b05080993b1cc96e197720aa6929bc9)
- [Enterprise Connect](https://ics.services.jamfcloud.com/icon/hash_99daa87dd697754db8c0fc4578612dcddefa290f5c698d4d398e32c7b782a6ce)
