### ISSUE TITLE
`"path":` in `policy_array` as command

### ISSUE THREAD

**Issue by amyers22** [dan-snelson/dialog-scripts#21]
Currently the `"path":` in `policy_array` is configured to look for a file path for verification the `listitem` completed. Would it be possible to add a `command` option for verification based on its output? 

https://github.com/dan-snelson/dialog-scripts/blob/5864bb613e1eda306bf5a0f553dc945cb59ea2fa/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L1235-L1247

**Comment by dan-snelson** [comment]
Thanks for the Feature Request, @amyers22.

Are you able to share a sanitized code sample for testing purposes?

**Comment by dan-snelson** [comment]
@amyers22: A quick reminder that I’m waiting on you for additional information; please above. Thanks.

**Comment by amyers22** [comment]
Not currently. This was more around the ability for the path to be set with something like `fdesetup status` and if its not on then the policy didnt complete. I know there are file paths to check for FileVault, but this would just be an example of a command output I would want to compare to.

**Comment by dan-snelson** [comment]
@amyers22 and @mbracco1973:

Please test-drive [`1.6.0-rc1`](https://github.com/dan-snelson/dialog-scripts/commit/1e03672b5584a9622cdeba75976fd147290232ae).

<img width="932" alt="Screenshot 2022-12-14 at 6 46 29 AM" src="https://user-images.githubusercontent.com/24623109/207613358-e109ba2d-d108-49db-976f-678a5b71719a.png">

---

**NOTES:**
- `policy_array`'s `path` has been replaced with `validation`
    - `validation` should **not** be blank; use `None` instead (Example [here](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L413).)
- 🆕 The `confirmPolicyExecution` function validates if the policy needs to be executed
- 🆕 The `validatePolicyResult` function validates if the policy succeeded
   - Specifying an absolute path for `validation` to simulate pre-`v1.6.0` behavior
   - When specifying a custom value for `validation`, use `None` for `trigger` (Example [here](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L342-L343) and [here](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L816-L845).)

**Comment by dan-snelson** [comment]
@amyers22 and @mbracco1973:

<img width="932" alt="Screenshot 2022-12-14 at 6 41 58 PM" src="https://user-images.githubusercontent.com/24623109/207754751-8b4c6645-82f3-4688-a6a6-dde7ad641cad.png">

[Setup Your Mac (1.6.0-rc3)](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash)

> Addresses [Issue No. 21](https://github.com/dan-snelson/dialog-scripts/issues/21)

- 🆕 The `confirmPolicyExecution` function confirms if the policy needs to be executed
- 🆕 The `validatePolicyResult` function validates if the policy succeeded
- :fire: `policy_array`'s `path` has been replaced with `validation`
- `validation` **must be** one of the following values:
  - Absolute path (simulates pre-v1.6.0 behavior, for example: `"/Applications/Microsoft Teams.app/Contents/Info.plist"`)
  - 🆕 `Local` (for local validation within the Setup Your Mac script; example [here](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L342-L343) and [here](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L827-L871))
  - 🆕 `Remote` (for remote validation via a Jamf Pro policies with single-script payloads; example validation script [here](https://github.com/dan-snelson/dialog-scripts/tree/issue-21/Setup%20Your%20Mac/Validations), with code [here](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L353-L354) and [here](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L873-L885).)
  - 🆕 `None` (for triggers which don't require validation, for example: `recon` as shown [here](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L423-L424))

**Comment by dan-snelson** [comment]
[Setup Your Mac (1.6.0-rc5)](https://github.com/dan-snelson/dialog-scripts/commit/0b4bdca39220faac0175d7c0e5657ea0e5cbc70a)
- Adds both local and remote policy validation for Palo Alto Networks GlobalProtect

<img width="932" alt="Screenshot 2022-12-16 at 5 22 17 AM" src="https://user-images.githubusercontent.com/24623109/208098948-9e899084-b944-464f-9274-ac222985f743.png">

**Comment by dan-snelson** [comment]
[Setup Your Mac (1.6.0-rc6)](https://github.com/dan-snelson/dialog-scripts/commit/c7dca4ac0c29f88f49c270e7efbbf8c589ced6a0)
- Adds local FileVault validation

<img width="932" alt="Screenshot 2022-12-16 at 12 54 06 PM" src="https://user-images.githubusercontent.com/24623109/208179646-b7354fc8-ad74-4a65-9f63-c07a8d0c5907.png">

**Comment by amyers22** [comment]
I dont deploy Sophos or GlobalProtect, but the FileVault validation works great!

**Comment by dan-snelson** [comment]
Thanks for confirming, @amyers22.

**Comment by dan-snelson** [comment]
Addressed in [Setup Your Mac (1.6.0)](https://snelson.us/2023/01/setup-your-mac-via-swiftdialog-1-6-0/).
