### ISSUE TITLE
Update Inventory changes user information in User & Location

### ISSUE THREAD

**Issue by robjschroeder** [dan-snelson/dialog-scripts#24]
https://github.com/dan-snelson/dialog-scripts/blob/20124791b432727d4e5028663714b07cc354cf93/Inventory%20Update%20Progress/swiftDialog-Inventory-Update-Progress.bash#L294

When updating inventory using this script, the jamf recon -endUsername command changes the value in the username field in the computer's inventory. In my case, our usernames are the user's UPN, but when this command is ran, it changes the record to a value that is not their UPN so all other user data is removed from User & Location.

**Comment by dan-snelson** [comment]
Thanks, @robjschroeder.

If you’re able to, please share what you’re using and I can add it as a comment.

**Comment by dan-snelson** [comment]
Greetings, @robjschroeder!

When you have cycles, please reply with _your_ Line No. 294.

Thanks.

**Comment by robjschroeder** [comment]
`/usr/local/bin/jamf recon --verbose >> "$inventoryLog" &`

This is my line 294 and 100

**Comment by dan-snelson** [comment]
Thanks, @robjschroeder.

Unless you have any objections, I'll go ahead an close this as resolved with the following `0.0.5` updates:
- [Lines 103 & 104](https://github.com/dan-snelson/dialog-scripts/blob/development/Inventory%20Update%20Progress/swiftDialog-Inventory-Update-Progress.bash#L103-L104)
- [Lines 298 & 299](https://github.com/dan-snelson/dialog-scripts/blob/development/Inventory%20Update%20Progress/swiftDialog-Inventory-Update-Progress.bash#L298-L299)

**Comment by robjschroeder** [comment]
I'm good with that, thank you!

**Comment by dan-snelson** [comment]
Resolved in [`0.0.5`](https://github.com/dan-snelson/dialog-scripts/blob/main/Inventory%20Update%20Progress/swiftDialog-Inventory-Update-Progress.bash)
