### ISSUE TITLE
help with jamf policy -event

### ISSUE THREAD

**Issue by CC007W** [dan-snelson/dialog-scripts#25]
Hello, First thank you for this. We are in the testing/pilot stages of mac rollout. I have been testing the script however, I have run into so troubles with using the custom event triggers.

Im editing this line:
 ```
 {
            "listitem": "Software",
            "icon": "99",
            "progresstext": "Please wait",
            "trigger_list": [
                {
                    "trigger": "working",
                    "path": "/Applications/Software/Test.app/Contents/Info.plist"
                }
            ]
        }
```
When I run Setup Your Mac from Self Service it fails instantly.
2022-12-22 09:00:00 - SETUP YOUR MAC DIALOG: listitem: index: 0, status: fail, statustext: Failed

However on the same macbook from Terminal. This works fine and installs the package
`sudo /usr/local/bin/jamf policy -event working`

Is there something obvious I'm missing here?

**Comment by dan-snelson** [comment]
Thanks for reaching out, @CC007W, and sorry to hear that your mileage is varying too greatly.

Please confirm that `policy_array` is valid JSON; see the **last** bullet of [Step E.2.3.2](https://snelson.us/2022/11/setup-your-mac-via-swiftdialog-1-5-0/#configuration).

**Comment by dan-snelson** [comment]
(You're also invited to join us on the [#setup-your-mac Mac Admins Slack Channel](https://snelson.us/2022/12/setup-your-mac-mac-admins-slack-channel/).)

**Comment by CC007W** [comment]
> 

Hello, Yes I did test everything in policy array and came back as Valid JSON

**Comment by dan-snelson** [comment]
Thanks for validating. 

I’m Terminal, when you run …
`sudo /usr/local/bin/jamf policy -event working`

… does it **actually** install:
`"/Applications/Software/Test.app/Contents/Info.plist"`

If not, that’s what’s “failing.”

**Comment by CC007W** [comment]
> Thanks for validating.
> 
> I’m Terminal, when you run … `sudo /usr/local/bin/jamf policy -event working`
> 
> … does it **actually** install: `"/Applications/Software/Test.app/Contents/Info.plist"`
> 
> If not, that’s what’s “failing.”

Yes once I run in Terminal that path is now there because I tried Setup your Mac after using terminal and I get an instant Installed message

**Comment by dan-snelson** [comment]
Interesting …

… is it a timing issue on the first execution?

(Setup Your Mac isn’t doing anything special to see if the file exists.)

**Comment by dan-snelson** [comment]
You may wish to try [1.6.0-rc9](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash) with a validation of `None`.

**Comment by dan-snelson** [comment]
Greetings, @CC007W!

Please advise the current status.

Thanks.

**Comment by CC007W** [comment]
Hello,
I tried using 1.6.0 with validation of `None` . The status immediately shows installed however, the package is never installed. I also tried moving down in order with no luck. Its as if `jamf policy -event` never kicks off

**Comment by dan-snelson** [comment]
Thanks for the update, @CC007W. 

Will you please direct-message me the logs on the Mac Admins Slack?

**Comment by dan-snelson** [comment]
Closing-the-loop for any other affected admins:

> - [Enhanced policy logging options](https://github.com/dan-snelson/dialog-scripts/blob/issue-21/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L782-L783)
>    - Search for and comment-out: `eval "${jamfBinary} policy -trigger ${trigger}"`
>    - Uncomment: `eval "${jamfBinary} policy -trigger ${trigger} -verbose | tee -a ${scriptLog}"`
>    - Ensure `debug mode` is set to `false`

**Comment by CC007W** [comment]
This solved my issue.
Ensure debug mode is set to false (since policies do not actually execute when debug mode is set to true)
