### ISSUE TITLE
Enrollment Complete: Keyboard Input

### ISSUE THREAD

**Issue by fresca25** [dan-snelson/dialog-scripts#27]
Hello Dan (Hope all is well on your end.)-

When a PreStage enrolled device upon sign-in > enrollment complete trigger Setup Your Mac 1.5.1 runs the "Welcome" window and has a glitch where the keyboard stops working and does not let data being entered to fields. Once I quit session and launch from self service the bug goes away allowing me to enter data using keyboard. 

This does not occur when doing user initiated enrollment I presume because it was launched from self service rather than enrollment complete. 

Environment
 - OS version 12.5/12.6/13.1
 - Intel and M1 tested on

**Comment by dan-snelson** [comment]
Greetings, @fresca25!

While an `enrollmentComplete` trigger _might_ work, Setup Your Mac is designed to be executed via Self Service; see [Implementation](https://snelson.us/2022/11/setup-your-mac-via-swiftdialog-1-5-0/#implementation). (As such, I’ll remove the “bug” flag on this issue.)

Are you able to confirm that an **actual** user is logged-in when things go sideways and **not** `_mbsetupuser` ?

**Comment by dan-snelson** [comment]
@fresca25 Does `swiftDialog` [Issue No. 146](https://github.com/bartreardon/swiftDialog/issues/146) describe what you’re experiencing?

**Comment by fresca25** [comment]
@dan-snelson it appears so! I don't have any issue with it launching but was unsure of if it was related to Setup Your Mac or SwiftDialog. 

Also, a user is logged-in and not _mbsetupuser I did confirm that.

**Comment by dan-snelson** [comment]
@fresca25: If you feel your issue is `swiftDialog`-related, please close this issue (and optionally add your use-case to [Issue No. 146](https://github.com/bartreardon/swiftDialog/issues/146).)

If you feel this issue is related to Setup Your Mac, please confirm and I'll try to replicate.

Thanks.
