### ISSUE TITLE
Icon URL Location no longer contains Hash for harvesting

### ISSUE THREAD

**Issue by rossmclaren** [dan-snelson/dialog-scripts#28]
When attempting to find the hash for an application's Self Service icon, the copied URL has now seemingly updated to the following scheme:

https://*******.jamfcloud.com/icon?id=30

Is there any way to use the updated icon URL's in the script, or will we need to look at adding the icons on to a machine via Pre-Stage first?

**Comment by dan-snelson** [comment]
Please see the following post:

https://macadmins.slack.com/archives/C04FRRN3281/p1672651110344059?thread_ts=1672515030.856079&channel=C04FRRN3281&message_ts=1672651110.344059

**Comment by robatjamf** [comment]
@rossmclaren Check your cloud services connection... under 

Settings -> Global -> Cloud services connection 

If that is not enabled or your activation code expired (check that too via your Jamf Nation Dashboard) then Jamf Pro will not upload your icons
