### ISSUE TITLE
Automate the swiftdialog app installation or version validation 

### ISSUE THREAD

**Issue by mani2care** [dan-snelson/dialog-scripts#32]
As discussed, we need a built in automation for the swift dialog version validation. If in case I am using old versions of swifdialog and install it latest version so it will help us to additional effort to do
Swiftdialogversion =$8any version /Autoupdate get always latest xyz version.

**Comment by dan-snelson** [comment]
Thanks, @mani2care!

**Comment by dan-snelson** [comment]
@mani2care:

After additional consideration, I'm going to close this as "not planned" as I can't see us every using this feature and your requirement is quite easily met by leveraging the Packages payload in your Jamf Pro policy.

<img width="1569" alt="Screenshot 2023-01-21 at 10 06 49 AM" src="https://user-images.githubusercontent.com/24623109/213878593-a246652b-c5d6-4f11-b28f-c557ebecfb09.png">
