### ISSUE TITLE
How to change the font color from white to black in the "welcomeBannerText"

### ISSUE THREAD

**Issue by midiman1000** [dan-snelson/dialog-scripts#38]
> **Note:** While all requests are welcome, finding available cycles to custom-code a feature we won't use in our production environment is always challenging.

**Is your feature request related to a problem? Please describe.**
A clear, concise description of the problem. (i.e., I'm frustrated when ...)

**Describe the solution you'd like**
A clear, concise description of what you want to happen.

**Describe alternatives you've considered**
A clear, concise description of any alternative solutions or features you've considered.

**Additional context**

**Comment by dan-snelson** [comment]
<img width="932" alt="Screenshot 2023-02-28 at 3 36 01 AM" src="https://user-images.githubusercontent.com/24623109/221829632-b9afcc6e-228e-452a-bba9-d71f105f6645.png">

```
dialog --bannerimage "https://img.freepik.com/free-photo/yellow-watercolor-paper_95678-446.jpg" --bannertext "Banner Text Goes Here" --titlefont "shadow=true, size=40, color=#000000" --message "Created via:  \n\ndialog --bannerimage 'https://img.freepik.com/free-photo/yellow-watercolor-paper_95678-446.jpg' --bannertext 'Banner Text Goes Here' --titlefont 'shadow=true, size=40, color=#000000'"
```
