### ISSUE TITLE
Code clean up - does policy_array in Setup-Your-Mac-via-Dialog.bash, still need to be a shell array?

### ISSUE THREAD

**Issue by wakco** [dan-snelson/dialog-scripts#39]
Not really a bug or a feature, more just code clean up.

Loving the use of JavaScript via osascript to handle reading JSON content, however I noticed something that I assume is to be cleaned up at some point. I assume this is a hangover from a DEPNotify based script, but I am struggling to see a reason why policy_array is still a shell array when it only contains one long JSON formatted string.

Figured I'd log it here as a helpful reminder to clean up policy_array, as I haven't gone through enough of the script yet to consider creating a pull request that cleans this up.

**Comment by dan-snelson** [comment]
Thanks, @wakco; PRs are always welcome.

**Comment by wakco** [comment]
https://github.com/dan-snelson/dialog-scripts/pull/45

**Comment by wakco** [comment]
Thank you.
