### ISSUE TITLE
Setup your Mac: Wait for dialog to close before exiting

### ISSUE THREAD

**Issue by pyther** [dan-snelson/dialog-scripts#4]
When running the `Setup your Mac.bash` script from a Jamf policy, the dialog window will automatically close once Jamf is done executing the policy. This does not give the user a chance to review the status and read the final message update. 

To resolve this issue, I added a `wait` statement before the `exit "${exitCode}"` in the `finalise` function.

**Comment by dan-snelson** [comment]
Nice, @pyther.

You're welcome to submit a PR (after I fix Issue #3).

**Comment by master-vodawagner** [comment]
@pyther 

Can you supply the wait statement you added? I'm encountering a similar issue with Jamf closing the dialog too quickly

**Comment by pyther** [comment]
PR: https://github.com/dan-snelson/dialog-scripts/pull/5

**Comment by dan-snelson** [comment]
https://snelson.us/2022/09/setup-your-mac-via-swiftdialog-1-2-7/#completion-action
