### ISSUE TITLE
LoggedInUser variable defined twice

### ISSUE THREAD

**Issue by sudoMyName** [dan-snelson/dialog-scripts#41]
- Script version 1.7.1

Lines 56 and 164 are duplicates which probably would throw anyone else off but I have a special workflow for our IT Ops team who are pre-provisioning computers for the end user.  This workflow hinges on If/Then statements based on the $loggedInUser value.

`loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }' )`

Thank you for an amazing tool!
Brandon Sexton

**Comment by dan-snelson** [comment]
The recent addition of [Line 107](https://github.com/dan-snelson/dialog-scripts/blob/main/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L107) is reliant on [Line 56](https://github.com/dan-snelson/dialog-scripts/blob/main/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L56), which, when called, exits at [Line 108](https://github.com/dan-snelson/dialog-scripts/blob/main/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L108).

**Comment by dan-snelson** [comment]
On second thought, @sudoMyName, you make an excellent point.

**Comment by dan-snelson** [comment]
Addressed in [1.7.2-rc2](https://github.com/dan-snelson/dialog-scripts/commit/7bdce45faa8ec963557b1ec4057c77b90958ebea).

**Comment by dan-snelson** [comment]
Addressed in [1.7.2](https://snelson.us/2023/02/setup-your-mac-via-swiftdialog-1-7-0/#1-7-2-28-feb-2023).
