### ISSUE TITLE
Move JSONs to remote location

### ISSUE THREAD

**Issue by astrugatch** [dan-snelson/dialog-scripts#43]
> **Note:** While all requests are welcome, finding available cycles to custom-code a feature we won't use in our production environment is always challenging.

This is specifically for SetUpYourMac

**Is your feature request related to a problem? Please describe.**

Not a problem, just a potential improvement

**Describe the solution you'd like**
Separate out code for JSONs (like the policy list) to separate files, that can be read from remote locations. Similar to the json-url option in Nudge.

If this is set up, a JAMF variable can be assigned for the URL. This would make the script more re-usable for different scenarios, rather than needing to be directly modified for each scenario.

**Comment by astrugatch** [comment]
I think this can be done by piping a curl of the json to jq in bash.

**Comment by wakco** [comment]
It can, but if you are going that far, I'd like to include grabbing from a .json file as well (cat vs curl).

Essentially anyone could replace:
`policy_array=('...')`
with:
`policy_array("$(cat /path/to/file.json)")`
For a file or for a URL:
`policy_array("$(curl -sL https://server.name/jsonquery)")`

**Comment by dan-snelson** [comment]
Thanks, @astrugatch and @wakco.

**Comment by dan-snelson** [comment]
@astrugatch:

Please take a look at @wakco's [instructions](https://github.com/dan-snelson/dialog-scripts/blob/development/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L535-L537) and advise if this satisfies this Feature Request.

Thanks.

**Comment by astrugatch** [comment]
Hi Dan,

This was what I did. (FYI I'm working off of 1.7.1 as 1.8 changes didn't impact us)

**I added this line to global variables:**
`jsonURL=${10}                                                               # URL Hosting JSON for policy_array`

**And this line replaces the entirety of the policy_array (~ line 503):**
` policy_array=("$(curl -sL $jsonURL)")`

**Comment by astrugatch** [comment]
That's fine with me. Thanks for the help getting me on the right track to implement it @wakco
