### ISSUE TITLE
Retry trigger after failed list item

### ISSUE THREAD

**Issue by DevliegereM** [dan-snelson/dialog-scripts#44]
**Is your feature request related to a problem? Please describe.**
This is something I ran into when deploying on an unstable WiFi connection (test devices)

**Describe the solution you'd like**
I'd like to have a retry option where you can specify how many times it should retry the trigger for a specific list item. Ofcourse for _None_ this is not applicable but it would be interesting to try this with _Local_ and _Remote_. Sometimes a network connection can fail and then the whole deployment fails because of one small hiccup, a retry might fix this issue and cause less issues for end-users. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dan-snelson** [comment]
@DevliegereM:

If you're using a `Remote` validation, couldn't you just include any additional retries?

**Comment by dan-snelson** [comment]
@DevliegereM:

After additional consideration, I feel this is best handled by a `Remote` validation.

I'll close this as "not planned" and you're invited to join us on the [#setup-your-mac](https://snelson.us/2022/12/setup-your-mac-mac-admins-slack-channel/) Mac Admins Slack Channel if your mileage varies too greatly.

Thanks.
