### ISSUE TITLE
Configuration:catch-all info showing in UI dialog unnecessary

### ISSUE THREAD

**Issue by mani2care** [dan-snelson/dialog-scripts#46]
Below info is unnecessary showing in dialog UI when in production model.

Configuration:catch-all ('welcome' dialog disable)
Configuration:catch-all (video)

![IMG_4741](https://user-images.githubusercontent.com/52978899/224957467-39ce5545-d69c-459f-a810-edacb7b0d45e.jpg)
![IMG_4742](https://user-images.githubusercontent.com/52978899/224957704-5cfad836-dd2b-44d5-8e93-bd504fdef3bb.jpg)

**Comment by dan-snelson** [comment]
@mani2care:

Thanks for the heads-up.

There's now a dedicated repo for SYM; please open this issue [there](https://github.com/dan-snelson/Setup-Your-Mac/issues/new/choose).
