### ISSUE TITLE
FR: Add Configuration to the ? output for help

### ISSUE THREAD

**Issue by master-vodawagner** [dan-snelson/dialog-scripts#47]
Hey @dan-snelson 

Just a simple FR I believe, would be good to add the chosen configuration to the help ? button which offers the computer information

**Comment by dan-snelson** [comment]
@master-vodawagner:

Thanks for the FR.

Sorry for any Dan-induced confusion; there's now a dedicated repo for SYM; will you please re-submit it [there](https://github.com/dan-snelson/Setup-Your-Mac/issues/new/choose)?
