### ISSUE TITLE
Deferral Drop Downs with Time Choices

### ISSUE THREAD

**Issue by midiman1000** [dan-snelson/dialog-scripts#48]
Hello, and love the work..!
The display is fantastic but besides being able to run an action in the last parameter, can we see about adding drop downs for deferrals, like a choice of time or date...? Just a thought as the display does things yes, but would like to present to the EU's for macOS updates or Upgrades to defer right in the pop up notification.

Thank you.

**Comment by dan-snelson** [comment]
Well, @midiman1000, it's now June and I doubt I'll _ever_ add this FR.

You may wish to take a look at Trevor's [Scripting User Deferrals with SwiftDialog](https://bigmacadmin.wordpress.com/2023/02/20/scripting-user-deferrals-with-swiftdialog/).

Closing as "not planned."

**Comment by midiman1000** [comment]
No worries I appreciate all the hard work thank you

John J Stevens
***@***.***
469-563-6538
JAMF Admin & Apple Engineer
https://www.linkedin.com/in/john-stevens-itspecialist
________________________________
