### ISSUE TITLE
Display Message curl needs -L

### ISSUE THREAD

**Issue by adem-kfs** [dan-snelson/dialog-scripts#51]
[Display-Message-via-Dialog.bash](https://github.com/dan-snelson/dialog-scripts/blob/main/Display%20Message/Display-Message-via-Dialog.bash) (and others?) using curl to find the latest swiftDialog repo URL also need the -L flag added to follow redirects.

This is on line 140 in v0.0.8

**Comment by dan-snelson** [comment]
Thanks, @adem-kfs!
