### ISSUE TITLE
Filevault validations

### ISSUE THREAD

**Issue by geekparadize** [dan-snelson/dialog-scripts#55]
Hello,

Where can I find the filevault validation script?

Best regards

**Comment by dan-snelson** [comment]
Greetings, @geekparadize!

The FileVault Validation is built-in to SYM …
https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L1944-L1975

… so you'll call it as a Local Validation:
https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L951-L952

If you haven't already, please join us over at the [#setup-your-mac](https://snelson.us/2022/12/setup-your-mac-mac-admins-slack-channel/) Mac Admins Slack Channel.
