### ISSUE TITLE
Output files not being created

### ISSUE THREAD

**Issue by seanjsgallagher** [dan-snelson/dialog-scripts#59]
> Before submitting a **Setup Your Mac** bug report, please review the [open swiftDialog issues](https://github.com/bartreardon/swiftDialog/issues) to help determine the source of the issue.

**Describe the bug**
Output files not being created.

**To Reproduce**
 - Please describe how the script was executed (i.e., via macOS Terminal, via in a Jamf Pro Self Service policy, etc.).
 - Please detail any modififications.
 
**Expected behavior**
A clear, concise description of what you expected to happen.

**Code/log output**
Please supply the full command used, and if applicable, add full output from Terminal. Either upload the log, or paste the output in a code block (triple backticks at the start and end of the code block, please!).

Password:
-e 2024-09-09 17:34:05 - 

###
# DEBUG MODE | Disk Usage (0.0.3)
###

macOS 14 installed; proceeding ...
-e 2024-09-09 17:34:05 - swiftDialog version 2.5.0.4768 found; proceeding...
-e 2024-09-09 17:34:05 - Create Welcome Dialog …
-e 2024-09-09 17:34:08 - c45879 clicked Continue …;
-e 2024-09-09 17:34:08 - Disk Space: 598.5 GB free ( 60.17% available )
-e 2024-09-09 17:34:08 - Analyze Disk Usage with Progress (1 of 2)
-e 2024-09-09 17:34:24 - Run "open /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-09-173404.txt" as "501" … 
The file /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-09-173404.txt does not exist.
-e 2024-09-09 17:34:24 - Run "open /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-09-173404.txt" as "501" … 
The file /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-09-173404.txt does not exist.
-e 2024-09-09 17:34:24 - Run "open x-apple.systempreferences:com.apple.settings.Storage" as "501" … 
-e 2024-09-09 17:34:24 - Quitting …
-e 2024-09-09 17:34:25 - Exiting …
-e 2024-09-09 17:34:25 - Removing /var/tmp/dialogWelcomeLog.Pee5 …
-e 2024-09-09 17:34:25 - Removing /var/tmp/dialogProgressLog.0jFt …
-e 2024-09-09 17:34:25 - Removing /var/tmp/dialogCompleteLog.i5i8 …
-e 2024-09-09 17:34:25 - Removing /var/tmp/diskUsageEntireVolumeTop50.rZYm …
-e 2024-09-09 17:34:25 - Removing /var/tmp/diskUsageUsersHomeTop50.nC1m …
-e 2024-09-09 17:34:25 - Goodbye!

**Screenshots**

**Environment (please complete the following information):**
 - OS version 14.6.1
 - Script version 0.0.3

**Additional context**

**Comment by seanjsgallagher** [comment]
Tried to execute from Terminal and Jamf. Same outcome.

**Comment by dan-snelson** [comment]
@seanjsgallagher:

Please ensure you're using version `0.0.4` and that you've set [`debugMode`](https://github.com/dan-snelson/dialog-scripts/blob/main/Disk%20Usage/Disk%20Usage%20with%20swiftDialog.bash#L61) to `false`.

**Comment by dan-snelson** [comment]
In single tests with both macOS Sonoma `14.6.1 (23G93)` and macOS Sequoia `15.0 (24A335)`, setting `debugMode` to `false` displayed the output as expected.

**Comment by seanjsgallagher** [comment]
I updated the script in Jamf, and set it to default as you suggested. My results were the same.

Logs:
<head></head>
[STEP 1 of 4]
--
Executing Policy Disk Usage with swiftDialog (0.0.4)
[STEP 2 of 4]
Running script Disk Usage 0.0.4...
Script exit code: 0
Script result: 2024-09-10 08:19:12 -  ### # Disk Usage (0.0.4) ###  macOS 14 installed; proceeding ... 2024-09-10 08:19:12 - swiftDialog version 2.5.0.4768 found; proceeding... 2024-09-10 08:19:12 - Create Welcome Dialog … 2024-09-10 08:19:15 - c45879 clicked Continue …; 2024-09-10 08:19:15 - Disk Space: 598.5 GB free ( 60.16% available ) 2024-09-10 08:19:15 - Analyze Disk Usage with Progress (1 of 2) 2024-09-10 08:19:15 - Analyze Disk Usage for "Macintosh HD" 2024-09-10 08:19:17 - Output disk usage statistics of "Macintosh HD" to: /var/tmp/diskUsageEntireVolumeTop50.zuNM 2024-09-10 08:20:45 - Elapsed Time for "Macintosh HD": 0h:1m:28s 2024-09-10 08:20:45 - Disk usage for volume "Macintosh HD" on computer "LHP937D7F4"  2024-09-10 08:20:45 - Report Location: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 402: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 403: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 404: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 405: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 406: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 407: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 408: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 409: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 410: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 411: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 412: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 413: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 414: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt: No such file or directory 2024-09-10 08:20:45 - Analyze Disk Usage with Progress (2 of 2) 2024-09-10 08:20:45 - Analyze Disk Usage for "/Users/c45879 /Users/c45879_1" 2024-09-10 08:20:46 - Output disk usage statistics of "/Users/c45879 /Users/c45879_1" to: /var/tmp/diskUsageUsersHomeTop50.YjE8 2024-09-10 08:20:47 - Elapsed Time for "/Users/c45879 /Users/c45879_1": 0h:0m:1s 2024-09-10 08:20:47 - Disk usage for "/Users/c45879 /Users/c45879_1" for volume "Macintosh HD" on computer "LHP937D7F4"  2024-09-10 08:20:47 - Report Location: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 430: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 431: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 432: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 433: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 434: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 435: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 436: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 437: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 438: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 439: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 440: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 441: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 442: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 448: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory /Library/Application Support/JAMF/tmp/Disk Usage 0.0.4: line 454: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt: No such file or directory 2024-09-10 08:20:50 - Run "open /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt" as "501" …  The file /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-081911.txt does not exist. 2024-09-10 08:20:50 - Run "open /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt" as "501" …  The file /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-081911.txt does not exist. 2024-09-10 08:20:50 - Run "open x-apple.systempreferences:com.apple.settings.Storage" as "501" …  2024-09-10 08:20:50 - Quitting … 2024-09-10 08:20:51 - Exiting … 2024-09-10 08:20:51 - Removing /var/tmp/dialogWelcomeLog.wtyT … 2024-09-10 08:20:51 - Removing /var/tmp/dialogProgressLog.C2r8 … 2024-09-10 08:20:51 - Removing /var/tmp/dialogCompleteLog.cDbY … 2024-09-10 08:20:51 - Removing /var/tmp/diskUsageEntireVolumeTop50.zuNM … 2024-09-10 08:20:51 - Removing /var/tmp/diskUsageUsersHomeTop50.YjE8 … 2024-09-10 08:20:51 - Goodbye!
[STEP 3 of 4]
[STEP 4 of 4]


Included screen shot to show my settings in the policy also.

<img width="1110" alt="Screenshot 2024-09-10 at 8 18 55 AM" src="https://github.com/user-attachments/assets/7ea49af6-fe21-4bf8-8b88-164652068e0a">

**Comment by dan-snelson** [comment]
@seanjsgallagher:

To eliminate variables, please install the [latest version of swiftDialog](https://github.com/swiftDialog/swiftDialog/releases) and execute a freshly downloaded copy of the [script](https://github.com/dan-snelson/dialog-scripts/blob/main/Disk%20Usage/Disk%20Usage%20with%20swiftDialog.bash) via an elevated Terminal session (after having set `debugMode` to `false`).

(Please also enclose logs and code with three backticks for easier reading.)

**Comment by seanjsgallagher** [comment]
```
Here is the latest output.
Hope I did the three backticks correct, never did them before. 

```Password:
```-e 2024-09-10 12:27:38 - 

```###
```# Disk Usage (0.0.4)
```###

```macOS 14 installed; proceeding ...
```-e 2024-09-10 12:27:38 - swiftDialog version 2.5.2.4777 found; proceeding...```
```-e 2024-09-10 12:27:38 - Create Welcome Dialog …```
```-e 2024-09-10 12:27:42 - c45879 clicked Continue …;```
```-e 2024-09-10 12:27:42 - Disk Space: 598.2 GB free ( 60.14% available )```
```-e 2024-09-10 12:27:42 - Analyze Disk Usage with Progress (1 of 2)
```-e 2024-09-10 12:27:42 - Analyze Disk Usage for "Macintosh HD"```
```-e 2024-09-10 12:27:43 - Output disk usage statistics of "Macintosh HD" to: /var/tmp/diskUsageEntireVolumeTop50.VKif```
```-e 2024-09-10 12:28:53 - Elapsed Time for "Macintosh HD": 0h:1m:10s```
```-e 2024-09-10 12:28:53 - Disk usage for volume "Macintosh HD" on computer "LHP937D7F4" ```
```-e 2024-09-10 12:28:53 - Report Location: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt```
```/Users/c45879/diskUsage.sh: line 402: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 403: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 404: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 405: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 406: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 407: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 408: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 409: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 410: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 411: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 412: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 413: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 414: /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt: No such file or directory```
```-e 2024-09-10 12:28:53 - Analyze Disk Usage with Progress (2 of 2)
```-e 2024-09-10 12:28:53 - Analyze Disk Usage for "/Users/c45879 /Users/c45879_1"
```-e 2024-09-10 12:28:54 - Output disk usage statistics of "/Users/c45879 /Users/c45879_1" to: /var/tmp/diskUsageUsersHomeTop50.3OmJ```
```-e 2024-09-10 12:28:55 - Elapsed Time for "/Users/c45879 /Users/c45879_1": 0h:0m:1s
```-e 2024-09-10 12:28:55 - Disk usage for "/Users/c45879 /Users/c45879_1" for volume "Macintosh HD" on computer "LHP937D7F4" ```
```-e 2024-09-10 12:28:55 - Report Location: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt```
```/Users/c45879/diskUsage.sh: line 430: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 431: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 432: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 433: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 434: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 435: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 436: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 437: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 438: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 439: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 440: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 441: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 442: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory
```
```/Users/c45879/diskUsage.sh: line 448: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory```
```/Users/c45879/diskUsage.sh: line 454: /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt: No such file or directory
```-e 2024-09-10 12:29:03 - Run "open /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt" as "501" … ```
```The file /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-122737.txt does not exist.```
```-e 2024-09-10 12:29:03 - Run "open /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt" as "501" …``` 
```The file /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-122737.txt does not exist.```
```-e 2024-09-10 12:29:03 - Run "open x-apple.systempreferences:com.apple.settings.Storage" as "501" … ```
```-e 2024-09-10 12:29:03 - Quitting …```
```-e 2024-09-10 12:29:05 - Exiting …```
```-e 2024-09-10 12:29:05 - Removing /var/tmp/dialogWelcomeLog.uVLL …```
```-e 2024-09-10 12:29:05 - Removing /var/tmp/dialogProgressLog.6Hsn …```
```-e 2024-09-10 12:29:05 - Removing /var/tmp/dialogCompleteLog.vRih …```
```-e 2024-09-10 12:29:05 - Removing /var/tmp/diskUsageEntireVolumeTop50.VKif …```
```-e 2024-09-10 12:29:05 - Removing /var/tmp/diskUsageUsersHomeTop50.3OmJ …```
```-e 2024-09-10 12:29:05 - Goodbye!```
```
```

**Comment by dan-snelson** [comment]
Sorry for any Dan-induced confusion, @seanjsgallagher; you only need a **total** of six (6) backticks: three (3) at the start and three (3) at the end:

```
Pre-formatted text goes here
``` 

---

I see swiftDialog is now the latest version; please confirm you're using a freshly downloaded copy of the [script](https://github.com/dan-snelson/dialog-scripts/blob/main/Disk%20Usage/Disk%20Usage%20with%20swiftDialog.bash).

**Comment by dan-snelson** [comment]
Here's a snippet of my output using a freshly downloaded copy (and after setting `debugMode` to `false`):

```
2024-09-10 12:50:51 - Report Location: /Users/dan/Desktop/SerialNumber-84e707-Volume-Usage-2024-09-10-124839.txt
2024-09-10 12:50:51 - Analyze Disk Usage with Progress (2 of 2)
2024-09-10 12:50:51 - Analyze Disk Usage for "/Users/dan"
2024-09-10 12:50:52 - Output disk usage statistics of "/Users/dan" to: /var/tmp/diskUsageUsersHomeTop50.QhFz
2024-09-10 12:52:27 - Elapsed Time for "/Users/dan": 0h:1m:35s
2024-09-10 12:52:27 - Disk usage for "/Users/dan" for volume "Macintosh HD" on computer "SerialNumber-84e707" 
2024-09-10 12:52:27 - Report Location: /Users/dan/Desktop/dan-Home-Usage-2024-09-10-124839.txt
2024-09-10 12:52:31 - Run "open /Users/dan/Desktop/SerialNumber-84e707-Volume-Usage-2024-09-10-124839.txt" as "502" … 
2024-09-10 12:52:31 - Run "open /Users/dan/Desktop/dan-Home-Usage-2024-09-10-124839.txt" as "502" … 
```

**Comment by seanjsgallagher** [comment]
I am using the latest Script, I even downloaded the latest again and used it again. 

   2024-09-10 14:01:21 - swiftDialog version 2.5.2.4777 found; proceeding...
   2024-09-10 14:01:21 - Create Welcome Dialog …
   2024-09-10 14:01:25 - c45879 clicked Continue …;
   2024-09-10 14:01:25 - Disk Space: 598.3 GB free ( 60.15% available )
   2024-09-10 14:01:25 - Analyze Disk Usage with Progress (1 of 2)
   2024-09-10 14:01:40 - Run "open /Users/c45879 /Users/c45879_1/Desktop/LHP937D7F4-Volume-                            Usage-2024-09-10-140120.txt" as "501" … 
   The file /Users/c45879_1/Desktop/LHP937D7F4-Volume-Usage-2024-09-10-140120.txt does not exist.
   2024-09-10 14:01:40 - Run "open /Users/c45879 /Users/c45879_1/Desktop/c45879-Home-Usage-                                          2024-09-10-140120.txt" as "501" … 
   The file /Users/c45879_1/Desktop/c45879-Home-Usage-2024-09-10-140120.txt does not exist.
   2024-09-10 14:01:40 - Run "open x-apple.systempreferences:com.apple.settings.Storage" as "501" … 
   2024-09-10 14:01:41 - Quitting …
   2024-09-10 14:01:42 - Exiting …
   2024-09-10 14:01:42 - Removing /var/tmp/dialogWelcomeLog.Eh0x …
   2024-09-10 14:01:42 - Removing /var/tmp/dialogProgressLog.OoXN …
   2024-09-10 14:01:42 - Removing /var/tmp/dialog
   2024-09-10 14:01:42 - Removing /var/tmp/diskUsageEntireVolumeTop50.c9ch …
   2024-09-10 14:01:42 - Removing /var/tmp/diskUsageUsersHomeTop50.YZFo …
   2024-09-10 14:01:42 - Goodbye!


[com.company.log](https://github.com/user-attachments/files/16949328/com.company.log)

**Comment by dan-snelson** [comment]
Does your user account include a trailing space, which is nested **inside** _another_ user's account? (i.e., ` /Users/c45879 `, then `/Users/c45879_1`)

```
dscl . read /Users/$(id -u -n) NFSHomeDirectory
```

(At this stage, you're welcome to [direct-message me](https://macadmins.slack.com/team/U120FAHK2) on the Mac Admins Slack.)
