### ISSUE TITLE
FR: Ability to force restart when Finish button is clicked 

### ISSUE THREAD

**Issue by master-vodawagner** [dan-snelson/dialog-scripts#7]
As we enable Filevault at the next login we want to be able to force a restart once the user clicks finish on Setup your Mac.

Any thoughts how this could be achieved?

**Comment by dan-snelson** [comment]
Doubt I'll add this into Setup Your Mac, @master-vodawagner.

The following may prove helpful:
[Forced and Dismissible Log Out, Restart or Shut Down Prompts](https://snelson.us/2022/07/log-out-restart-shut-down/)
